global:
  scrape_interval: 5s # Ambil data setiap 5 detik

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-containers'
    static_configs:
      - targets: ['cadvisor:8080'] # Mengambil data dari container cAdvisor